version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # build . assumes a docker file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      # look here for node modules don't map
      - .:/app
      # map outside folder to current folder
  tests:
    # 2nd container
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # build . assumes a docker file
    volumes:
      - /app/node_modules
      # look here for node modules don't map
      - .:/app
    command: ["npm","run","test"]